### ISSUE TITLE
Readme.md API

### ISSUE THREAD

**Issue by Mokerstier** [dewarian/web-app-from-scratch-2021#10]
Je mag wat meer toelichting geven over de API hoeveel requests kan ik doen bijvoorbeeld?

Welke API gebruik je eigenlijk je zegt in je readme iets over spaceX maar je app laat anime characters zien.

help me i'm lost

**Comment by bommezijn** [comment]
Hoi, 
Bedankt voor de feedback, Dat klopt, wegens de complexiteit van de SpaceX API en de onbetrouwbaarheid daarvan ben ik overgestapt naar eentje die wel betrouwbaar is.

Readme en styling zal geupdate worden.
- [x] Readme aanpassen naar huidig concept.
- [x] Styling aanpassen naar huidig concept.

**Comment by bommezijn** [comment]
Gedeeltelijk opgelost in [commit #07221f](https://github.com/dewarian/web-app-from-scratch-2021/commit/07221f).

Readme is aangepast en herstructureert.

**Comment by bommezijn** [comment]
Styling is geupdatet naar huidig concept.
