### ISSUE TITLE
Readme.md Conventions

### ISSUE THREAD

**Issue by Mokerstier** [dewarian/web-app-from-scratch-2021#11]
Ik zie dat je veel bezig bent met conventies, prettier etc. maar dit is nog onderbelicht in je readme

**Comment by bommezijn** [comment]
Hoi,

Bedankt voor de feedback. Ik zal de readme updaten.

**Comment by bommezijn** [comment]
Conventies zijn geupdatet in [commit #07221f](https://github.com/dewarian/web-app-from-scratch-2021/commit/07221f).
