### ISSUE TITLE
Gitmoji?

### ISSUE THREAD

**Issue by Mokerstier** [dewarian/web-app-from-scratch-2021#12]
Gebruik je toevallig gitmoji conventie in je commits?

SUPER NICE!!
i'm a fan!

Maar vergeet niet dit ook te benoemen in je readme!
#bonuspunten!

**Comment by bommezijn** [comment]
Hoi,

Bedankt, Ik zal de readme updaten met conventies voor git commits.

**Comment by bommezijn** [comment]
Conventies zijn up to date naar de gebruikte conventies in [commit #07221f](https://github.com/dewarian/web-app-from-scratch-2021/commit/07221f).
