### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by Mokerstier** [dewarian/web-app-from-scratch-2021#13]
https://github.com/dewarian/web-app-from-scratch-2021/blob/21b0f2a2480d8a6f5dabb1c97804aacda7944838/static/js/modules/router.js#L16

Kun je de URL niet opdelen in aparte stukjes bijv:

const endpoint = kitsu.io/api/edge/anime?;
const year = filter[seasonYear]=2021;

etc.

en dan als je gaat fetchen plak je alles aan elkaar en doe je:
const url = endpoint+year+etc.

**Comment by bommezijn** [comment]
Hoi,

Bedankt voor de feedback. Ik zal de `getData` functie, polijsten naar een schoner product door middel van modular endpoints.

**Comment by bommezijn** [comment]
Opgelost in commit [c80bd4](https://github.com/dewarian/web-app-from-scratch-2021/commit/c80bd4).
