### ISSUE TITLE
jsdocs

### ISSUE THREAD

**Issue by shabier** [dewarian/web-app-from-scratch-2021#2]
incorrect param type, use string

https://github.com/dewarian/web-app-from-scratch-2021/blob/dbb5140b9196c3201c7014995d51c5300654ba86/js/index.js#L11

**Comment by bommezijn** [comment]
Thank you for pointing out the param type.
[Fixed.](https://github.com/dewarian/web-app-from-scratch-2021/commit/489131f07ea7ad151bfa6746a1efa9227d8fb308)
