### ISSUE TITLE
Render function 

### ISSUE THREAD

**Issue by shabier** [dewarian/web-app-from-scratch-2021#4]
Move this call to your main function; you want to be able to control everything (or much as possible) from one place

https://github.com/dewarian/web-app-from-scratch-2021/blob/dbb5140b9196c3201c7014995d51c5300654ba86/js/index.js#L17

**Comment by bommezijn** [comment]
Understood the intent of the issue and removed the render from the `getData()`. Moved to the invoking function of the application.
[See commit 365b745](https://github.com/dewarian/web-app-from-scratch-2021/commit/365b745).
