### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by shabier** [dewarian/web-app-from-scratch-2021#5]
These functions can be a module on their own. Export them using `export function...`, import them in your main js file using `import { getdata } from './api.js'`, and then call them

https://github.com/dewarian/web-app-from-scratch-2021/blob/dbb5140b9196c3201c7014995d51c5300654ba86/js/index.js#L14

https://github.com/dewarian/web-app-from-scratch-2021/blob/dbb5140b9196c3201c7014995d51c5300654ba86/js/index.js#L28

**Comment by bommezijn** [comment]
Incorporated the modular approach within the project.

Thank you for the feedback.
